log:
  level: debug
connector:
  blockchain:
    # other public RPCs can be found: https://docs.tezos.com/architecture/rpc#public-and-private-rpc-nodes
    rpc: https://rpc.ghostnet.teztnets.com
    network: ghostnet
    signatory: http://127.0.0.1:6732
persistence:
  type: leveldb
  leveldb:
    path: ./.leveldb
ffcore:
  url: http://127.0.0.1:5101
  namespaces:
    - tezos
confirmations:
  required: 0
  fetchReceiptUponEntry: true
transactions:
  handler:
    name: simple
